version: '3.9'

services:
 frontend:
  container_name: frontend
  image: frontend
  build: ./frontend
  ports:
   - 4210:80
  depends_on:
   - java_app
 java_app:
  container_name: backend
  image: backend
  build: ./backend
  ports:
  - 9001:8080
  environment:
  - DATABASE_URL=jdbc:postgresql://java_db:5432/db_tests
  - DATABASE_USERNAME=postgres
  - DATABASE_PWD=admin123
  depends_on:
  - java_db
 java_db:
  container_name: java_db
  image: postgres:16
  ports:
  - 5432:5432
  environment:
  - POSTGRES_USER=postgres
  - POSTGRES_PASSWORD=admin123
  - POSTGRES_DB=db_tests