version: '3.4'
services:
  mysql:
    container_name: lunna_mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: RootL3g3ndary++!
#      MYSQL_ROOT_HOST: 172.18.0.1
    # mysql_native_password is obsolete due to weak encryption. However, new sha256 is not available in Workbench yet.
    command: --init-file=/etc/mysql/conf.d/init.sql --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
      - ./init.sql:/etc/mysql/conf.d/init.sql
